/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.test.demo;

import static gradle.test.demo.factory.BrowserFactory.driver;
import static gradle.test.demo.factory.BrowserFactory.driverQuit;

public class App {
    public static void loadPage() {
        driver.get("https://www.google.com/");
        System.out.println("page loaded");
    }

    public static void main(String[] args) {
        loadPage();
        driverQuit();
    }
}
